using System.Text.Json.Serialization;

namespace SnykGhe.Core.GitHub.Manifest
{
    /// <summary>
    /// The GitHub App manifest posted to <c>/settings/apps/new</c> to pre-fill an App registration.
    /// Property names map to the GitHub manifest schema (snake_case) via <see cref="JsonPropertyNameAttribute"/>.
    /// </summary>
    public sealed record GitHubAppManifest
    {
        [JsonPropertyName("name")]
        public required string Name { get; init; }

        /// <summary>Homepage URL (required by GitHub).</summary>
        [JsonPropertyName("url")]
        public required string Url { get; init; }

        [JsonPropertyName("description")]
        public string? Description { get; init; }

        [JsonPropertyName("hook_attributes")]
        public required GitHubAppHookAttributes HookAttributes { get; init; }

        /// <summary>Where GitHub redirects with the temporary code after the App is created.</summary>
        [JsonPropertyName("redirect_url")]
        public required string RedirectUrl { get; init; }

        /// <summary>Where GitHub redirects a user after they install the App.</summary>
        [JsonPropertyName("setup_url")]
        public string? SetupUrl { get; init; }

        /// <summary>Also redirect to the setup URL when an installation's permissions/repos are updated.</summary>
        [JsonPropertyName("setup_on_update")]
        public bool SetupOnUpdate { get; init; }

        [JsonPropertyName("public")]
        public bool Public { get; init; }

        [JsonPropertyName("default_permissions")]
        public required IReadOnlyDictionary<string, string> DefaultPermissions { get; init; }

        [JsonPropertyName("default_events")]
        public required IReadOnlyList<string> DefaultEvents { get; init; }
    }

    public sealed record GitHubAppHookAttributes
    {
        [JsonPropertyName("url")]
        public required string Url { get; init; }

        [JsonPropertyName("active")]
        public bool Active { get; init; } = true;
    }

    /// <summary>
    /// Response from <c>POST /app-manifests/{code}/conversions</c>. The pem and webhook secret are
    /// generated by GitHub and returned exactly once.
    /// </summary>
    public sealed record ManifestConversionResponse
    {
        [JsonPropertyName("id")]
        public long Id { get; init; }

        [JsonPropertyName("slug")]
        public string? Slug { get; init; }

        [JsonPropertyName("pem")]
        public string? Pem { get; init; }

        [JsonPropertyName("webhook_secret")]
        public string? WebhookSecret { get; init; }

        [JsonPropertyName("client_id")]
        public string? ClientId { get; init; }

        [JsonPropertyName("client_secret")]
        public string? ClientSecret { get; init; }

        [JsonPropertyName("html_url")]
        public string? HtmlUrl { get; init; }
    }
}
