namespace SnykGhe.Core.Secrets
{
    /// <summary>
    /// Persists App credentials generated by the registration flow. Implementations target the platform's
    /// secret store (Key Vault, Secrets Manager); a no-op variant covers local development.
    /// </summary>
    public interface IAppCredentialStore
    {
        /// <summary>True when secrets are durably persisted; false for the display-only fallback.</summary>
        bool PersistsSecrets { get; }

        /// <summary>Human-readable destination, shown on the success page (e.g. "Azure Key Vault (my-vault)").</summary>
        string Describe();

        Task WriteAsync(AppCredentials credentials, CancellationToken cancellationToken = default);
    }
}
