using Amazon.SecretsManager;
using Amazon.SQS;
using Azure.Extensions.AspNetCore.Configuration.Secrets;
using Azure.Identity;
using Azure.Messaging.ServiceBus;
using Microsoft.ApplicationInsights.Extensibility;
using Octokit.Webhooks;
using SnykGhe.Core.Configuration;
using SnykGhe.Service.Configuration;
using SnykGhe.Core.Fix;
using SnykGhe.Core.GitHub;
using SnykGhe.Core.GitHub.Manifest;
using SnykGhe.Core.Messaging;
using SnykGhe.Core.Processing;
using SnykGhe.Core.Secrets;
using SnykGhe.Core.Snyk;
using SnykGhe.Core.Storage;
using SnykGhe.Core.Webhooks;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddOptions<GitHubOptions>()
    .Bind(builder.Configuration.GetSection(GitHubOptions.SectionName));

builder.Services
    .AddOptions<SnykOptions>()
    .Bind(builder.Configuration.GetSection(SnykOptions.SectionName));

builder.Services
    .AddOptions<StorageOptions>()
    .Bind(builder.Configuration.GetSection(StorageOptions.SectionName));

builder.Services
    .AddOptions<ServiceBusOptions>()
    .Bind(builder.Configuration.GetSection(ServiceBusOptions.SectionName));

builder.Services
    .AddOptions<SqsOptions>()
    .Bind(builder.Configuration.GetSection(SqsOptions.SectionName));

builder.Services
    .AddOptions<RegistrationOptions>()
    .Bind(builder.Configuration.GetSection(RegistrationOptions.SectionName));

builder.Services
    .AddOptions<SecretRepositoryOptions>()
    .Bind(builder.Configuration.GetSection(SecretRepositoryOptions.SectionName));

var storageProvider = builder.Configuration
    .GetSection(StorageOptions.SectionName)
    .GetValue<StorageProvider>(nameof(StorageOptions.Provider));

if (storageProvider == StorageProvider.DynamoDb)
{
    builder.Services.AddSingleton<IGitHubInstallationRegistry, DynamoDbGitHubInstallationRegistry>();
    builder.Services.AddSingleton<IAppConfigStore, DynamoDbAppConfigStore>();
    builder.Services.AddSingleton<IScanCoordinationStore, DynamoDbScanCoordinationStore>();
}
else
{
    builder.Services.AddSingleton<IGitHubInstallationRegistry, TableStorageGitHubInstallationRegistry>();
    builder.Services.AddSingleton<IAppConfigStore, TableAppConfigStore>();
    builder.Services.AddSingleton<IScanCoordinationStore, TableStorageScanCoordinationStore>();
}

builder.Services.AddHostedService<GitHubInstallationRegistryInitializer>();
builder.Services.AddSingleton<GitHubClientFactory>();
builder.Services.AddSingleton<OrgPolicyResolver>();
builder.Services.AddSnykScanning(builder.Configuration);
builder.Services.AddSingleton<FixPlanner>();
builder.Services.AddSingleton<IManifestPatcher, NuGetManifestPatcher>();
builder.Services.AddSingleton<FixPullRequestService>();
builder.Services.AddSingleton<RepositoryCloner>();
builder.Services.AddSingleton<PullRequestCheckService>();
builder.Services.AddSingleton<ScanCoalescer>();
builder.Services.AddSingleton<BaselineScanService>();
builder.Services.AddSingleton<WebhookEventProcessor, GitHubWebhookEventProcessor>();
builder.Services.AddSingleton<WebhookDispatcher>();

// Durable webhook queue: Service Bus on Azure, SQS on AWS; in-process channel otherwise (local dev).
var serviceBusOptions = builder.Configuration
    .GetSection(ServiceBusOptions.SectionName)
    .Get<ServiceBusOptions>();

var sqsOptions = builder.Configuration
    .GetSection(SqsOptions.SectionName)
    .Get<SqsOptions>();

if (serviceBusOptions?.IsConfigured == true)
{
    builder.Services.AddSingleton(_ => new ServiceBusClient(
        serviceBusOptions.FullyQualifiedNamespace,
        new DefaultAzureCredential()));
    builder.Services.AddSingleton<IWebhookQueue, ServiceBusWebhookQueue>();
    builder.Services.AddHostedService<ServiceBusWebhookWorker>();
}
else if (sqsOptions?.IsConfigured == true)
{
    builder.Services.AddSingleton<IAmazonSQS>(_ =>
        string.IsNullOrWhiteSpace(sqsOptions.AwsRegion)
            ? new AmazonSQSClient()
            : new AmazonSQSClient(Amazon.RegionEndpoint.GetBySystemName(sqsOptions.AwsRegion)));
    builder.Services.AddSingleton<IWebhookQueue, SqsWebhookQueue>();
    builder.Services.AddHostedService<SqsWebhookWorker>();
}
else
{
    builder.Services.AddSingleton<ChannelWebhookQueue>();
    builder.Services.AddSingleton<IWebhookQueue>(sp => sp.GetRequiredService<ChannelWebhookQueue>());
    builder.Services.AddHostedService<ChannelWebhookWorker>();
}

// Self-service App registration (manifest flow) + post-install setup page.
builder.Services.AddHttpClient<GitHubAppManifestService>();
builder.Services.AddSingleton<RegistrationStateProtector>();

var secretsOptions = builder.Configuration
    .GetSection(SecretRepositoryOptions.SectionName)
    .Get<SecretRepositoryOptions>();

var secretStoreProvider = secretsOptions?.Provider ?? SecretStoreProvider.None;
var secretsAwsRegion = secretsOptions?.AwsRegion;

// The GitHub App private key and webhook secret are generated by the registration flow and written to Key
// Vault — never seeded by the deploy template. Load them from Key Vault at runtime (mapped onto GitHub:*
// config keys) so a fresh deploy needs no placeholder secrets and infra redeploys cannot clobber the
// registration-written values. Picked up on the next app start (restart after registering).
if (secretStoreProvider == SecretStoreProvider.AzureKeyVault && !string.IsNullOrWhiteSpace(secretsOptions?.KeyVaultUri))
{
    builder.Configuration.AddAzureKeyVault(
        new Uri(secretsOptions.KeyVaultUri),
        new DefaultAzureCredential(),
        new AzureKeyVaultConfigurationOptions
        {
            Manager = new GitHubCredentialSecretManager(
                secretsOptions.PrivateKeySecretName,
                secretsOptions.WebhookSecretName),
        });
}

switch (secretStoreProvider)
{
    case SecretStoreProvider.AzureKeyVault:
        builder.Services.AddSingleton<IAppCredentialStore, KeyVaultAppCredentialStore>();
        break;
    case SecretStoreProvider.AwsSecretsManager:
        builder.Services.AddSingleton<IAmazonSecretsManager>(_ =>
            string.IsNullOrWhiteSpace(secretsAwsRegion)
                ? new AmazonSecretsManagerClient()
                : new AmazonSecretsManagerClient(Amazon.RegionEndpoint.GetBySystemName(secretsAwsRegion)));
        builder.Services.AddSingleton<IAppCredentialStore, SecretsManagerAppCredentialStore>();
        break;
    default:
        builder.Services.AddSingleton<IAppCredentialStore, DisplayOnceAppCredentialStore>();
        break;
}

// Application Insights for the processing tier. Enabled only when a connection string is configured, so
// local runs and non-Azure hosts stay quiet. Ingestion authenticates with the ambient managed identity
// rather than an embedded instrumentation key, matching how the app reaches its other Azure resources.
if (!string.IsNullOrWhiteSpace(builder.Configuration["APPLICATIONINSIGHTS_CONNECTION_STRING"]))
{
    builder.Services.AddApplicationInsightsTelemetry();
    builder.Services.Configure<TelemetryConfiguration>(
        config => config.SetAzureTokenCredential(new DefaultAzureCredential()));
}

builder.Services.AddControllers();

var app = builder.Build();

app.MapControllers();

app.Run();
