using Azure.Extensions.AspNetCore.Configuration.Secrets;
using Azure.Security.KeyVault.Secrets;
using SnykGhe.Core.Configuration;

namespace SnykGhe.Service.Configuration
{
    /// <summary>
    /// Maps the registration-written Key Vault secrets onto the configuration keys the app binds. The
    /// private key and webhook secret are generated by the manifest-registration flow (not the deploy
    /// template), so they are read from Key Vault at runtime rather than injected as env vars. Only those
    /// two secrets are loaded; everything else in the vault is ignored.
    /// </summary>
    public sealed class GitHubCredentialSecretManager : KeyVaultSecretManager
    {
        private readonly string _privateKeySecretName;
        private readonly string _webhookSecretName;

        public GitHubCredentialSecretManager(string privateKeySecretName, string webhookSecretName)
        {
            _privateKeySecretName = privateKeySecretName;
            _webhookSecretName = webhookSecretName;
        }

        public override bool Load(SecretProperties properties) =>
            string.Equals(properties.Name, _privateKeySecretName, StringComparison.Ordinal) ||
            string.Equals(properties.Name, _webhookSecretName, StringComparison.Ordinal);

        public override string GetKey(KeyVaultSecret secret)
        {
            if (string.Equals(secret.Name, _privateKeySecretName, StringComparison.Ordinal))
            {
                return $"{GitHubOptions.SectionName}:{nameof(GitHubOptions.PrivateKeyPem)}";
            }

            if (string.Equals(secret.Name, _webhookSecretName, StringComparison.Ordinal))
            {
                return $"{GitHubOptions.SectionName}:{nameof(GitHubOptions.WebhookSecret)}";
            }

            return secret.Name;
        }
    }
}
